import { createHash } from 'node:crypto'
import { realpathSync } from 'node:fs'
import { mkdtemp, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { resolve, sep } from 'node:path'
import { canonicalJson, sha256 } from './skill-lock.ts'

const LIMIT = 256_000
const ID = /^[A-Za-z0-9][A-Za-z0-9_.-]{0,127}$/
export type CliPreparationAdapter = { kind: 'codex-exec' | 'claude-print'; executable: string; id: string; model: string }
export interface PreparationCapability { taskRevisionId: string; specHash: string; verify(): boolean }
export interface CliPreparationDraft { schema: 'research-cli-preparation-draft-v1'; taskRevisionId: string; specHash: string; adapter: { id: string; model: string; identity: string }; inputHash: string; configHash: string; contentHash: string; code: string; patch: string | null; usage: null; humanApprovalRequired: true }
async function read(stream: ReadableStream<Uint8Array>) { const r=stream.getReader(),c:Uint8Array[]=[];let n=0;try{while(true){const x=await r.read();if(x.done)break;n+=x.value.byteLength;if(n>LIMIT)throw new Error('CLI preparation output exceeds limit');c.push(x.value)}return Buffer.concat(c).toString('utf8')}finally{r.releaseLock()} }
function command(a: CliPreparationAdapter,p:string){if(!ID.test(a.id)||!a.model||!a.executable||/[\0\r\n]/.test(a.executable))throw new Error('invalid admitted CLI adapter');return a.kind==='codex-exec'?[a.executable,'exec','--json','--sandbox','read-only','--model',a.model,p]:[a.executable,'-p',p,'--output-format','json','--model',a.model]}
/** Calls only a verified capability in an empty staging directory; it never applies output. */
export async function prepareCliDraft(input:{workspaceRoot:string;workspaceScope:string;instructions:string;maxRuntimeMs:number;adapter:CliPreparationAdapter;capability:PreparationCapability;credentialHome:string}):Promise<CliPreparationDraft>{
 if(!input.capability.verify()||!ID.test(input.capability.taskRevisionId)||!/^sha256:[a-f0-9]{64}$/.test(input.capability.specHash)||!Number.isSafeInteger(input.maxRuntimeMs)||input.maxRuntimeMs<1||input.maxRuntimeMs>600000)throw new Error('invalid approved CLI preparation capability')
 const root=realpathSync(resolve(input.workspaceRoot)),requested=resolve(root,input.workspaceScope);if(requested!==root&&!requested.startsWith(`${root}${sep}`))throw new Error('workspace scope escapes root');const scope=realpathSync(requested);if(scope!==root&&!scope.startsWith(`${root}${sep}`))throw new Error('workspace scope escapes root')
 const approved=Object.freeze({taskRevisionId:input.capability.taskRevisionId,specHash:input.capability.specHash,workspaceScope:input.workspaceScope,instructions:input.instructions,maxRuntimeMs:input.maxRuntimeMs}),config=Object.freeze({kind:input.adapter.kind,id:input.adapter.id,model:input.adapter.model,executable:input.adapter.executable}),prompt=`Return JSON only with code and optional patch. Do not execute tools, train, edit files, or request permissions. Approved task ${approved.taskRevisionId}: ${input.instructions}`,stage=await mkdtemp(`${tmpdir()}${sep}oph-cli-prep-`)
 try{const child=Bun.spawn(command(input.adapter,prompt),{cwd:stage,stdout:'pipe',stderr:'pipe',detached:process.platform!=='win32',env:{PATH:process.env.PATH??'',HOME:input.credentialHome,USERPROFILE:input.credentialHome}});let kill:ReturnType<typeof setTimeout>|undefined;const timer=setTimeout(()=>{try{process.kill(-child.pid,'SIGTERM')}catch{child.kill()}kill=setTimeout(()=>{try{process.kill(-child.pid,'SIGKILL')}catch{child.kill()}},1000)},input.maxRuntimeMs);const [stdout,stderr,exit]=await Promise.all([read(child.stdout as ReadableStream<Uint8Array>),read(child.stderr as ReadableStream<Uint8Array>),child.exited]);clearTimeout(timer);if(kill)clearTimeout(kill);if(exit!==0)throw new Error(`admitted CLI preparation failed: ${stderr.slice(0,512)}`);const raw=JSON.parse(stdout) as {code?:unknown;patch?:unknown};if(typeof raw.code!=='string'||!raw.code||raw.code.length>LIMIT||(raw.patch!==undefined&&typeof raw.patch!=='string'))throw new Error('CLI preparation returned an invalid draft');const patch=typeof raw.patch==='string'?raw.patch:null,contentHash=`sha256:${createHash('sha256').update(canonicalJson({code:raw.code,patch})).digest('hex')}`;return Object.freeze({schema:'research-cli-preparation-draft-v1',taskRevisionId:approved.taskRevisionId,specHash:approved.specHash,adapter:{id:config.id,model:config.model,identity:`${config.kind}:${config.executable}`},inputHash:sha256(canonicalJson(approved)),configHash:sha256(canonicalJson(config)),contentHash,code:raw.code,patch,usage:null,humanApprovalRequired:true})}finally{await rm(stage,{recursive:true,force:true})}
}
